# Generated by Django 5.1.3 on 2024-12-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('state_of_origin', models.CharField(max_length=100)),
                ('program_of_choice', models.CharField(max_length=100)),
                ('parent_guardian_name', models.CharField(max_length=255)),
                ('parent_guardian_phone', models.CharField(max_length=15)),
                ('birth_certificate', models.FileField(upload_to='documents/')),
                ('academic_transcripts', models.FileField(upload_to='documents/')),
                ('medical_fitness_report', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
