# Generated by Django 5.1.3 on 2024-12-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_adms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionform',
            name='academic_transcripts',
            field=models.FileField(upload_to='documents/academic_transcripts/'),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='birth_certificate',
            field=models.FileField(upload_to='documents/birth_certificates/'),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='medical_fitness_report',
            field=models.FileField(upload_to='documents/medical_reports/'),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='state_of_origin',
            field=models.CharField(max_length=50),
        ),
    ]
