# Generated by Django 5.1.3 on 2024-12-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_adms', '0003_candidatesubmission_cbtquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('cbt_score', models.FloatField()),
                ('utme_score', models.FloatField()),
                ('application_details', models.JSONField()),
                ('interview_score', models.FloatField()),
                ('health_status_valid', models.BooleanField()),
                ('admission_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
