# Generated by Django 5.1.3 on 2024-12-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_adms', '0004_candidate_alter_admissionform_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmittedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('programme', models.CharField(max_length=100)),
                ('admission_year', models.IntegerField()),
                ('serial_number', models.IntegerField(unique=True)),
                ('matriculation_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
