# Generated by Django 5.1.3 on 2024-12-04 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_adms', '0005_admittedcandidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admittedcandidate',
            name='name',
        ),
        migrations.AddField(
            model_name='admittedcandidate',
            name='candidate',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admitted_candidate', to='student_adms.candidate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admittedcandidate',
            name='serial_number',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
