# Generated by Django 5.1.3 on 2024-12-07 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_adms', '0006_remove_admittedcandidate_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=100)),
                ('programme', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('admitted_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_adms.admittedcandidate')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_adms.course')),
            ],
            options={
                'unique_together': {('admitted_candidate', 'course')},
            },
        ),
    ]
