# Generated by Django 5.1.3 on 2024-12-07 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_adms', '0007_course_courseregistration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseregistration',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='admitted_candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_registrations', to='student_adms.admittedcandidate'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_registrations', to='student_adms.course'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='registration_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
