# Generated by Django 5.1.3 on 2024-12-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_adms', '0009_courseregistration_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='registration_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
